// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCONU2irrhiVT_O8fQYDeMkcUuHXJ7AI_4',
    appId: '1:929846223381:web:061e5bac426a333052641c',
    messagingSenderId: '929846223381',
    projectId: 'yappingtime-66f94',
    authDomain: 'yappingtime-66f94.firebaseapp.com',
    storageBucket: 'yappingtime-66f94.firebasestorage.app',
    measurementId: 'G-0B1SRJSV85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCxflhQly57QFphZ0eOzIQqEt6E8nJpbE',
    appId: '1:929846223381:android:7bc5e8827c54dd0b52641c',
    messagingSenderId: '929846223381',
    projectId: 'yappingtime-66f94',
    storageBucket: 'yappingtime-66f94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU_ZRUjiJvE-IX8j3kejg40nK5Y51Fy1w',
    appId: '1:929846223381:ios:1d6bcccf3038496d52641c',
    messagingSenderId: '929846223381',
    projectId: 'yappingtime-66f94',
    storageBucket: 'yappingtime-66f94.firebasestorage.app',
    iosBundleId: 'com.example.yappingtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU_ZRUjiJvE-IX8j3kejg40nK5Y51Fy1w',
    appId: '1:929846223381:ios:1d6bcccf3038496d52641c',
    messagingSenderId: '929846223381',
    projectId: 'yappingtime-66f94',
    storageBucket: 'yappingtime-66f94.firebasestorage.app',
    iosBundleId: 'com.example.yappingtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCONU2irrhiVT_O8fQYDeMkcUuHXJ7AI_4',
    appId: '1:929846223381:web:96699ca04436471152641c',
    messagingSenderId: '929846223381',
    projectId: 'yappingtime-66f94',
    authDomain: 'yappingtime-66f94.firebaseapp.com',
    storageBucket: 'yappingtime-66f94.firebasestorage.app',
    measurementId: 'G-2B9BSM5DEL',
  );
}
