// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOmpcQ-iDJfvG5lxbFCqVmYhmB7B1bZx4',
    appId: '1:1090571344443:web:32df06222eaf5e5d209a1e',
    messagingSenderId: '1090571344443',
    projectId: 'yappingtime-801a6',
    authDomain: 'yappingtime-801a6.firebaseapp.com',
    storageBucket: 'yappingtime-801a6.firebasestorage.app',
    measurementId: 'G-F2HHXZZX9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq89OuauGQwmhVUBXsad_fQ9-wxgzFJiY',
    appId: '1:1090571344443:android:9c420b05e0102d14209a1e',
    messagingSenderId: '1090571344443',
    projectId: 'yappingtime-801a6',
    storageBucket: 'yappingtime-801a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFFuIj-8bW-2dkjIkuERR6u_N9xFzQvDI',
    appId: '1:1090571344443:ios:f5445a92a62f9183209a1e',
    messagingSenderId: '1090571344443',
    projectId: 'yappingtime-801a6',
    storageBucket: 'yappingtime-801a6.firebasestorage.app',
    iosBundleId: 'com.example.yappingtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFFuIj-8bW-2dkjIkuERR6u_N9xFzQvDI',
    appId: '1:1090571344443:ios:f5445a92a62f9183209a1e',
    messagingSenderId: '1090571344443',
    projectId: 'yappingtime-801a6',
    storageBucket: 'yappingtime-801a6.firebasestorage.app',
    iosBundleId: 'com.example.yappingtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOmpcQ-iDJfvG5lxbFCqVmYhmB7B1bZx4',
    appId: '1:1090571344443:web:75d59c7b0d07c274209a1e',
    messagingSenderId: '1090571344443',
    projectId: 'yappingtime-801a6',
    authDomain: 'yappingtime-801a6.firebaseapp.com',
    storageBucket: 'yappingtime-801a6.firebasestorage.app',
    measurementId: 'G-W64CD2H37F',
  );

}